version: '3'

vars:
  DOCKER_APP_NAME: scheduler
  DOCKER_IMAGE_NAME: taskscheduler

tasks:
  run:
    desc: run project
    cmds:
      - go run cmd/app/main.go
  
  test-1-App:
    desc: test app
    cmds:
      - go test -run ^TestApp$ ./tests

  test-3-nextDate:
    desc: run TestNextDate
    cmds:
      - go test -run ^TestNextDate$ ./tests
  
  test-4-addTask:
    desc: run TestAddTask
    cmds:
      - go test -run ^TestAddTask$ ./tests
       
  test-5-Tasks:
    desc: run TestTasks
    cmds:
      - go test -run ^TestTasks$ ./tests

  test-6-editTasks:
    desc: run TestEditTask
    cmds:
      - go test -run ^TestEditTask$ ./tests
  
  test-7-done:
    desc: run TestDone
    cmds:
      - go test -run ^TestDone$ ./tests
  
  test-all:
    desc: run all tests
    cmds:
      - go test ./tests

  clean-test-cache:
    cmds:
      - go clean -testcache
  
  rm-db:
    cmds:
      - rm -f scheduler.db
  
  curl-test-api:
    vars:
      TaskID: '{{.TaskID | default 1 }}'
    cmds:
      - curl -v "http://localhost:7540/api/task?id={{.TaskID}}"

  docker:build:
    desc: Build docker image
    cmds:
      - docker build --progress plain -t {{.DOCKER_IMAGE_NAME}}:v1 .
  
  docker:build-no-cache:
    desc: Build docker image
    cmds:
      - docker build --progress plain --no-cache -t {{.DOCKER_IMAGE_NAME}}:v1 .

  docker:run:
    desc: Run docker image (default port 7540)
    cmds:
      - docker run --name {{.DOCKER_APP_NAME}} -p 7540:7540 -d {{.DOCKER_IMAGE_NAME}}:v1
      - sleep 2
      - docker ps | grep {{.DOCKER_APP_NAME}}

  docker:stop:
    desc: Stop runnng docker container
    cmds:
      - docker container stop {{.DOCKER_APP_NAME}}
  
  docker:rm-container:
    cmds:
      - docker container stop {{.DOCKER_APP_NAME}}
      - docker container rm {{.DOCKER_APP_NAME}}
  
  docker:run-it:
    cmds:
      - docker run -it --rm -p 7540:7540 {{.DOCKER_IMAGE_NAME}}:v1 bash